# Generated by Django 6.0 on 2025-12-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekna_app', '0002_document_doc_size_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_org',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekna_app.organization'),
        ),
    ]
